### ISSUE TITLE
Broken webkitgtk package error when running 'hc scaffold example forum'

### ISSUE THREAD

**Issue by DrewMcArthur** [holochain/holonix-archive#1090] opened 2023-01-14 22:35 UTC
In the [basic installation guide](https://developer.holochain.org/install/), I'm instructed to run
 
```
nix-shell https://holochain.love --run "hc scaffold example forum"
```

However, this yields the following error

```
holochain-workspace % nix-shell https://holochain.love --run "hc scaffold example forum"
error: Package ‘webkitgtk-2.38.2+abi=4.0’ in /nix/store/62v5iyzgyk71cp1rbwj2f5mb1lkwirih-source/pkgs/development/libraries/webkitgtk/default.nix:241 is marked as broken, refusing to evaluate.

       a) To temporarily allow broken packages, you can use an environment variable
          for a single invocation of the nix tools.

            $ export NIXPKGS_ALLOW_BROKEN=1

        Note: For `nix shell`, `nix build`, `nix develop` or any other Nix 2.4+
        (Flake) command, `--impure` must be passed in order to read this
        environment variable.

       b) For `nixos-rebuild` you can set
         { nixpkgs.config.allowBroken = true; }
       in configuration.nix to override this.

       c) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
         { allowBroken = true; }
       to ~/.config/nixpkgs/config.nix.
(use '--show-trace' to show detailed location information)
```

I'm not sure if this is an error on holochain end (i.e. version needs to be updated in your packages) or if I can safely follow one of their suggestions, but if that's the case then the installation guide should mention what to do in this case.

ps. not sure if this is the correct repo to be submitting this issue, if not please redirect me and i'd be happy to resubmit elsewhere!

**Comment by DrewMcArthur** [comment] 2023-01-14 22:57
[searching for `webkitgtk` within the holochain organization](https://github.com/search?q=org%3Aholochain+webkitgtk&type=code) yields a few results in the [holochain-nixpkgs](https://github.com/holochain/holochain-nixpkgs) repo, so maybe this issue belongs there.

I see [PR#908](https://github.com/holochain/holochain-nixpkgs/pull/908) is open, which attempts to improve darwin support, so maybe this bug should be mentioned there.

Anyways, both of the locations that `webkitgtk` is mentioned in code/config don't mention any version numbers, so i'm not sure how I would update them.  maybe holochain.love just needs to get an updated build, that automatically would bump the version of `webkitgtk`?  With that in mind, is there a way to run `nix-shell https://holochain.love`, except pointing to a more recent version? or one that would rebuild with latest dependencies?

**Comment by DrewMcArthur** [comment] 2023-01-15 19:33
[update in this comment on docs-pages#347](https://github.com/holochain/docs-pages/issues/347#issuecomment-1383232381) 

> `nix-shell https://holochain.love --run "hc scaffold example forum"`
> 
> trying this command again today (without the temporary env variable in the comment above) and it appears to be working! must have been a temporary issue. i'll leave this open so that somebody on the holochain team sees this, but feel free to close this out!

**Comment by steveej** [comment] 2023-02-10 13:58
closing this as a duplicate of https://github.com/holochain/holochain/issues/1764#issuecomment-1384378377

**Closed as completed by steveej** 2023-02-10 13:58 UTC
